---
# # 服务器前置任务(ubuntu使用)
- name: Pre_tasks for Ubuntu
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt-get -y install python
     ignore_errors: True


# # 核心任务

- name: Zabbix
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: "common"}      
    - { role: zabbix, tags: "zabbix"}
    - { role: end, tags: "end"}