---
- name: Zabbix
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'zabbix_version_selection'
      prompt: "\nWhich Zabbix distribution do you want to use? [ 1/2/3/4 ] \n\n
      1: Zabbix 5.2\n
      2: Zabbix 5.0\n
      3: Zabbix 4.0\n
      4: Zabbix 3.0\n"
      private: no
      default: 1

  vars: 
    zabbix_version_select:
      '1': '5.2'
      '2': '5.0'
      '3': '4.0'
      '4': '3.0'

    zabbix_version: "{{zabbix_version_select[zabbix_version_selection]}}" 

  roles:
    - { role: role_common, tags: "role_common"} 
    - { role: role_cloud, tags: "role_cloud" }
    - { role: role_mysql, tags: "role_mysql" }
    - { role: role_docker, tags: "role_docker" }
    - { role: role_nginx, tags: "role_nginx" }
    - { role: zabbix, tags: "zabbix"}
    - { role: role_init, tags: "role_init"}
    - { role: role_preend, tags: "role_preend"}
    - { role: role_end, tags: "role_end"}
