- block:
  - name: Init for azure
    shell: waagent -deprovision+user --force  
    when: cloud == "azure"

  - name: Remove SSH info
    file: 
      path: '{{item}}'
      state: absent
    with_items:
      - /home/{{ansible_user_id}}/.ssh
      - /root/.ssh
      - /home/frapper/.ssh
    when: cloud == "none"
  when: init == 1