---
- set_fact:
    zabbix_repo: "https://repo.zabbix.com/zabbix{{zabbix_version}}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{zabbix_meta[zabbix_version].release}}+{{ansible_distribution_release}}_all.deb"
    zabbix_apt: "{{zabbix_meta[zabbix_version][install].Ubuntu}}"

- name: Install Zabbinx repo
  apt:
    deb: "{{zabbix_repo}}"
    update_cache: yes
    autoremove: yes

- name: Install Zabbix
  apt:
    name: "{{zabbix_apt}}"
    state: latest