- name: Create a zabbix dir
  file: 
    state: directory
    path: /data/wwwroot/zabbix

- name: copy .env and docker-compose file
  template: 
    src: '{{item.src}}'
    dest: '/data/wwwroot/zabbix'
  with_items:
    - {src: .env_agent,dest: /data/wwwroot/zabbix/.env_agent}
    - {src: .env_db_mysql,dest: /data/wwwroot/zabbix/.env_db_mysql}
    - {src: .env_db_mysql_proxy,dest: /data/wwwroot/zabbix/.env_db_mysql_proxy}
    - {src: .env_java,dest: /data/wwwroot/zabbix/.env_java}
    - {src: .env_prx,dest: /data/wwwroot/zabbix/.env_prx}
    - {src: .env_prx_mysql,dest: /data/wwwroot/zabbix/.env_prx_mysql}
    - {src: .env_srv,dest: /data/wwwroot/zabbix/.env_srv}
    - {src: .env_web,dest: /data/wwwroot/zabbix/.env_web}
    - {src: 'docker-compose-{{zabbix_version}}.yml',dest: /data/wwwroot/zabbix/docker-compose.yml}

- name: Use docker-compose run zabbix
  shell: | 
    docker-compose up -d
    sleep 30
  args:
    chdir: /data/wwwroot/zabbix

# check service and version
- name: Copy script files to remote
  copy: src=check_dockerapp_service.sh dest=/tmp/check_dockerapp_service.sh

- name: Check dockerapp service
  shell: bash /tmp/check_dockerapp_service.sh
  register: check_dockerapp_service
  notify: check_dockerapp_service
    
- name: Check zabbix version
  shell: >
    sudo echo "zabbix version:" $(docker images |grep zabbix-server |cut -d- -f4) |sudo tee -a /data/logs/install_version.txt  
  
    
