#0 Prepare
- name: Delete Zabbix files for re-install
  shell: |
    rm -rf /etc/zabbix
    rm -rf /usr/share/zabbix 
    
#1 Install by OS_family
- include: "{{ansible_os_family}}.yml"

#2 Import database
- name: Rename SQL zip file
  shell: ln -sf /usr/share/doc/zabbix-server-mysql*/create.sql.gz  /etc/zabbix 
  
- name: Restore database for MySQL
  mysql_db:
    login_user: zabbix
    login_password: "{{zabbix_db_root_password}}"
    name: zabbix
    state: import
    target: /etc/zabbix/create.sql.gz

#3 Configure Zabbix
- name: Set DBpassword on zabbix_server.conf for Zabbix-Server Connection
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '# DBPassword='
    line: DBPassword={{zabbix_db_root_password}}
    backrefs: yes

- block:
  - name: Restart Zabbix and apache service
    service:
      name: "{{item}}"
      state: restarted
      enabled: yes
    with_items:
      - zabbix-server
      - zabbix-agent
      - apache

  - name: Restart php-fpm for CentOS
    service:
      name: php-fpm
      state: restarted
      enabled: yes
    when: ansible_os_family == "RedHat"

#4 Extra Settings
- name: Set soft link
  shell: |
    ln -sf /usr/share/zabbix  /data/wwwroot
    ln -sf /etc/zabbix  /usr/share/zabbix/conf
    ln -sf /etc/zabbix  /data/config
    ln -sf /etc/httpd/conf.d/zabbix.conf  /etc/httpd/vhost
    ln -sf /var/log/zabbix  /data/logs

- name: Check Zabbix-Server Service
  shell: systemctl status zabbix-server | grep Active*
  register: check_zabbix_server_service
  notify: check_zabbix_server_service

- name: Check Zabbix-Agent Service
  shell: systemctl status zabbix-agent | grep Active*
  register: check_zabbix_agent_service
  notify: check_zabbix_agent_service

- name: Check Zabbix Version
  shell: sudo echo "zabbix_server --version |sed -n 1p" >>/data/logs/install_version.txt
