---
    - name: Dwonload zabbix.deb for ubuntu
      get_url:
        url: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
        dest: ~/zabbix.deb

    - name: Install zabbix.deb
      command: dpkg -i ~/zabbix.deb

    - name: update cache
      apt:
        update_cache: yes

    - name: Install zabbix-server-mysql zabbix-frontend-php zabbix-agent
      apt: 
        name: [zabbix-server-mysql, zabbix-frontend-php, zabbix-agent]
        state: latest

    - name: Create a new database with name 'zabbix'
      mysql_db:
        login_user: root
        name: zabbix
        encoding: utf8
        collation: utf8_bin
        state: present
        
    - name: Create database user with name 'zabbix' and password with all database privileges
      mysql_user:
        name: zabbix
        password: KNyQ45W2&4
        priv: 'zabbix.*:ALL'
        state: present

    - name: unarchive data.sql.gz fot LTS version
      command: gzip -d /usr/share/doc/zabbix-server-mysql/create.sql.gz
      when: version=='LTS'

    - name: unarchive data.sql.gz for latest version 
      command: gzip -d /usr/share/zabbix-server-mysql/{{item}}
      with_items:
        - schema.sql.gz
        - images.sql.gz
        - data.sql.gz
      when: version=='latest'

    - name: Restore database fot LTS version
      mysql_db:
        login_user: zabbix
        login_password: KNyQ45W2&4
        name: zabbix
        state: import
        target: /usr/share/doc/zabbix-server-mysql/create.sql
      when: version=='LTS'

    - name: Restore database for latest version 
      mysql_db:
        login_user: zabbix
        login_password: KNyQ45W2&4
        name: zabbix
        state: import
        target: /usr/share/zabbix-server-mysql/{{item}}
      with_items:
        - schema.sql
        - images.sql
        - data.sql
      when: version=='latest'

    - name: Change zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '# DBPassword='
        line: DBPassword=KNyQ45W2&4

    - name: Replace apache.conf
      template:
        src: apache.conf
        dest: /etc/zabbix/apache.conf

    - name: Restart service
      service:
        name: "{{item}}"
        state: restarted
        enabled: yes
      with_items:
        - zabbix-server
        - zabbix-agent
        - apache2