#1 Install by OS_family
- include: "{{ansible_os_family}}.yml"

#2 Import database
- name: unarchive data.sql.gz
  command: "zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -u zabbix -p{{zabbix_db_root_password}} zabbix"

#3 Configure Zabbix

- name: Set language code to support zh-CN
  shell: locale-gen zh_CN.UTF-8

- block:
  - name: Restart Zabbix and apache service
    service:
      name: "{{item}}"
      state: restarted
      enabled: yes
    with_items:
      - zabbix-server
      - zabbix-agent
      - apache

  - name: Restart php-fpm for CentOS
    service:
      name: php-fpm
      state: restarted
      enabled: yes
    when: ansible_os_family == RedHat

#4 Extra Settings
- name: Set soft link
  shell: |
    ln -sf /usr/share/zabbix  /data/wwwroot
    ln -sf /etc/zabbix  /data/config
    ln -sf /etc/httpd/conf.d/zabbix.conf  /etc/httpd/vhost

- name: Check Zabbix-Server Service
  shell: systemctl status zabbix-server | grep Active*
  register: check_zabbix_server_service
  notify: check_zabbix_server_service

- name: Check Zabbix-Agent Service
  shell: systemctl status zabbix-agent | grep Active*
  register: check_zabbix_agent_service
  notify: check_zabbix_agent_service
