---
- set_fact:
    zabbix_repo: "https://repo.zabbix.com/zabbix/{{zabbix_version}}//rhel/{{ansible_distribution_major_version}}/x86_64/zabbix-release-{{zabbix_meta[zabbix_version].release}}.el{{ansible_distribution_major_version}}.noarch.rpm"
    zabbix_yum: "{{zabbix_meta[zabbix_version][install].CentOS}}"

- name: Install Zabbinx repo
  yum:
    name: "{{zabbix_repo}}"
    state: latest
    update_cache: yes

- name: Set zabbix.repo
  lineinfile:
    dest: /etc/yum.repos.d/zabbix.repo
    regexp: enabled=0
    line: enabled=1
    backrefs: yes

- name: Install Zabbix on CentOS8
  yum: 
    name: "{{zabbix_yum}}"
    state: latest
  when: ansible_distribution_major_version != "7"

- name: Install Zabbix on CentOS7
  yum: 
    name: [zabbix-server-mysql, zabbix-web-mysql-scl, zabbix-agent, zabbix-apache-conf-scl]
    state: latest
  when: ansible_distribution_major_version == "7"